name: ocr
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - cpuonly=1.0=0
  - pytorch=1.8.2=py3.7_cpu_0
  - torchvision=0.9.2=py37_cpu
  - pytesseract=0.3.8
  - opencv=4.5.3
  - pip:
    - python-docx==0.8.11
    - numpy==1.19.5
    - streamlit==1.2.0
    - scikit-image
    - imutils
    - scipy
    - vietocr==0.3.5